semi: false
tabWidth: 2
trailingComma: "all"
jsxSingleQuote: true
printWidth: 65
singleQuote: true
arrowParens: "always"
proseWrap: "always"
plugins:
  - "./node_modules/prettier-plugin-svelte"
overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"
